# NumPy — Introduction (Chapter 1)

This chapter is a complete, beginner-friendly introduction to NumPy. It assumes zero prior knowledge and explains why NumPy is essential for scientific computing in Python.

## Learning Objectives

After completing this chapter you will be able to:

- Explain what NumPy is and where it is used
- Install and import NumPy
- Create and inspect an `ndarray`
- Compare NumPy arrays with Python lists
- Understand advantages and limitations of NumPy
- See concrete real-world application examples

## What is NumPy?

NumPy (Numeric Python) is the fundamental package for numerical computing in Python. It provides:

- A powerful N-dimensional array object (`ndarray`)
- Fast vectorized operations (element-wise arithmetic)
- Utilities for linear algebra, random number generation, Fourier transforms, and more

NumPy is implemented in C and exposes efficient low-level arrays and operations to Python, enabling high performance.

## Why NumPy?

Key reasons to use NumPy in data science and numerical computing:

1. Performance: NumPy arrays are implemented in contiguous memory and operations are vectorized (avoids Python loops).
2. Expressiveness: concise syntax for array math and broadcasting rules enable compact code.
3. Interoperability: most scientific Python libraries (pandas, scikit-learn, TensorFlow) use NumPy arrays as inputs/outputs.
4. Ecosystem: strong numeric and linear algebra routines built-in or accessible via SciPy.

## NumPy vs Python Lists — Overview

Compare key differences, with examples and measurements to illustrate why `ndarray` is preferred for numerical work:


In [2]:
"""
NumPy vs Python List Performance Comparison

This program compares:
1. Python List + List Comprehension
2. NumPy Vectorized Operations

Operation:
Square Root Calculation
"""

# Import required libraries
import timeit
import numpy as np
from math import sqrt

# ==========================================================
# Create Data
# ==========================================================

# Python List
python_list = list(range(10000))

# NumPy Array
numpy_array = np.arange(10000)

# ==========================================================
# Method 1 : Python List Comprehension
# ==========================================================

def python_list_sqrt():
    """
    Calculate square root using Python list comprehension
    """
    return [sqrt(x) for x in python_list]

# ==========================================================
# Method 2 : NumPy Vectorized Operation
# ==========================================================

def numpy_sqrt():
    """
    Calculate square root using NumPy vectorization
    """
    return np.sqrt(numpy_array)

# ==========================================================
# Display Sample Outputs
# ==========================================================

print("=" * 60)
print("SAMPLE OUTPUTS")
print("=" * 60)

print("\nPython List Result (First 10 Values)")
print(python_list_sqrt()[:10])

print("\nNumPy Result (First 10 Values)")
print(numpy_sqrt()[:10])

# ==========================================================
# Performance Testing
# ==========================================================

print("\n" + "=" * 60)
print("PERFORMANCE COMPARISON")
print("=" * 60)

# Time Python List Method
python_time = timeit.timeit(
    python_list_sqrt,
    number=100
)

# Time NumPy Method
numpy_time = timeit.timeit(
    numpy_sqrt,
    number=100
)

# ==========================================================
# Results
# ==========================================================

print(f"\nPython List Time : {python_time:.6f} seconds")
print(f"NumPy Array Time : {numpy_time:.6f} seconds")

# ==========================================================
# Speed Comparison
# ==========================================================

speedup = python_time / numpy_time

print(f"\nNumPy is approximately {speedup:.2f} times faster")

# ==========================================================
# Memory Comparison
# ==========================================================

print("\n" + "=" * 60)
print("MEMORY COMPARISON")
print("=" * 60)

# Python list memory estimate
python_memory = len(python_list) * 8

# NumPy memory
numpy_memory = numpy_array.nbytes

print(f"Python List Elements : {len(python_list)}")
print(f"NumPy Array Elements : {numpy_array.size}")

print(f"\nApprox Python Memory : {python_memory:,} bytes")
print(f"NumPy Memory         : {numpy_memory:,} bytes")

# ==========================================================
# Array Information
# ==========================================================

print("\n" + "=" * 60)
print("NUMPY ARRAY DETAILS")
print("=" * 60)

print("Shape      :", numpy_array.shape)
print("Dimension  :", numpy_array.ndim)
print("Size       :", numpy_array.size)
print("Data Type  :", numpy_array.dtype)
print("Item Size  :", numpy_array.itemsize)
print("Total Bytes:", numpy_array.nbytes)

# ==========================================================
# Conclusion
# ==========================================================

print("\n" + "=" * 60)
print("CONCLUSION")
print("=" * 60)

print("""
1. NumPy uses vectorized operations.
2. NumPy executes calculations using optimized C code.
3. NumPy avoids Python loops.
4. NumPy is generally much faster for numerical computations.
5. NumPy uses contiguous memory storage.
6. NumPy is preferred for:
   - Data Science
   - Machine Learning
   - Deep Learning
   - Scientific Computing
   - Data Analytics
""")

SAMPLE OUTPUTS

Python List Result (First 10 Values)
[0.0, 1.0, 1.4142135623730951, 1.7320508075688772, 2.0, 2.23606797749979, 2.449489742783178, 2.6457513110645907, 2.8284271247461903, 3.0]

NumPy Result (First 10 Values)
[0.         1.         1.41421356 1.73205081 2.         2.23606798
 2.44948974 2.64575131 2.82842712 3.        ]

PERFORMANCE COMPARISON

Python List Time : 0.121870 seconds
NumPy Array Time : 0.002042 seconds

NumPy is approximately 59.68 times faster

MEMORY COMPARISON
Python List Elements : 10000
NumPy Array Elements : 10000

Approx Python Memory : 80,000 bytes
NumPy Memory         : 80,000 bytes

NUMPY ARRAY DETAILS
Shape      : (10000,)
Dimension  : 1
Size       : 10000
Data Type  : int64
Item Size  : 8
Total Bytes: 80000

CONCLUSION

1. NumPy uses vectorized operations.
2. NumPy executes calculations using optimized C code.
3. NumPy avoids Python loops.
4. NumPy is generally much faster for numerical computations.
5. NumPy uses contiguous memory storage.
6. Num

### Explanation

- The Python list approach executes `sqrt` in Python for each element, which is slow because of interpreter overhead.
- NumPy's `np.sqrt` is implemented in C and applies the operation over the array in optimized loops, making it much faster for large numeric workloads.

## Installation

Install NumPy using `pip` or `conda`. Choose the one matching your environment.

**Using pip**
```

**Using conda** (recommended for data science environments):
```

Notes: On Windows or certain platforms, installing via `conda` may be simpler because `conda` manages binary dependencies.

## Importing NumPy

The widely used convention is to import NumPy as `np`:

```python

Always use this alias in examples and production code for readability and consistency.

In [3]:
# Import NumPy with standard alias
import numpy as np
# Create a simple ndarray and inspect key attributes
array_example = np.array([1, 2, 3], dtype=np.int64)
# Print representation, shape, dtype and memory size
print('array_example ->', array_example)
print('shape:', array_example.shape)
print('dtype:', array_example.dtype)
print('itemsize (bytes per element):', array_example.itemsize)
print('nbytes (total bytes):', array_example.nbytes)

array_example -> [1 2 3]
shape: (3,)
dtype: int64
itemsize (bytes per element): 8
nbytes (total bytes): 24


## `ndarray` — the core NumPy object

An `ndarray` (N-dimensional array) is a fixed-size, homogeneous container for items of the same data type. Key characteristics:

- Homogeneous: all elements have the same `dtype`
- Shape: tuple of integers describing the size in each dimension
- Memory layout: contiguous block of memory (C- or Fortran-order)
- Efficient: operations are implemented in C, minimizing Python overhead

In [5]:
# Examples of creating ndarrays with different shapes and dtypes
import numpy as np
# 1-D array of floats
a = np.array([1.0, 2.5, 3.14], dtype=np.float64)
# 2-D array (matrix)
matrix = np.array([[1, 2, 3], [4, 5, 6]], dtype=np.int32)
# 3-D array (tensor)
tensor = np.zeros((2, 3, 4), dtype=np.float32)
print('a:', a)
print('matrix shape:', matrix.shape)
print('tensor dtype:', tensor.dtype,tensor)

a: [1.   2.5  3.14]
matrix shape: (2, 3)
tensor dtype: float32 [[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


## Advantages of NumPy

- Speed: vectorized operations implemented in C minimize Python-level loops.
- Memory efficiency: compact contiguous arrays reduce overhead compared to Python lists.
- Rich API: linear algebra, random, FFTs, and more are available.
- Interoperability with other libraries like pandas, scikit-learn, TensorFlow, and PyTorch.

## Limitations of NumPy

- Homogeneous types only: cannot store mixed Python objects efficiently (use `object` dtype at significant cost).
- Not ideal for very small arrays where Python overhead is negligible.
- Limited out-of-core support: arrays must fit in memory (use Dask or memory-mapped files for large data).
- Broadcasting and advanced indexing can be confusing at first — understand rules to avoid unexpected results.

## Real-world Applications

NumPy is used across many domains:

- Data analysis and preprocessing (pandas uses NumPy internally)
- Machine learning (scikit-learn matrices, feature arrays)
- Deep learning (tensor manipulation, initial numpy-based prototypes)
- Scientific computing and simulations (numerical models, PDE solvers)
- Image processing (arrays of pixel values)
- Finance (time-series analysis and numeric computations)

In [6]:
# Real-world mini-example: normalize a feature vector (common in ML preprocessing)
import numpy as np
# Feature vector (single sample with 4 features)
features = np.array([10.0, 200.0, 3.5, 0.2])
# Compute mean and std and normalize (z-score)
mean = features.mean()
std = features.std()
normalized = (features - mean) / (std if std != 0 else 1.0)
print('original:', features)
print('normalized:', normalized)

original: [ 10.  200.    3.5   0.2]
normalized: [-0.51270072  1.73054941 -0.58944349 -0.6284052 ]


## Notes, Warnings and Common Errors

- Forgetting to import NumPy (`import numpy as np`) causes `NameError`.
- Mixing dtypes implicitly can lead to surprising upcasts (e.g., mixing ints and floats yields floats).
- Indexing outside bounds raises `IndexError`.
- Use `np.copy()` when you need an independent copy; assignment can create views.
- Beware of integer division in Python 2 (not an issue in Python 3 where `/` is float division).

## Interview Tips

- Be ready to explain the difference between Python lists and NumPy arrays in terms of memory layout and performance.
- Understand broadcasting rules and give simple examples.
- Know common ndarray attributes (`shape`, `dtype`, `ndim`, `size`).
- Practice writing concise vectorized code instead of loops.

## Summary

NumPy provides an efficient N-dimensional array object and essential numeric routines. It is the backbone of scientific Python and a required skill for data science and machine learning.

## Interview Questions — Beginner (10) with Answers

1. What is NumPy?

Answer: NumPy is a Python library for numerical computing that provides the `ndarray` and vectorized operations.
2. How do you import NumPy?

Answer: `import numpy as np`.
3. What is an `ndarray`?

Answer: An N-dimensional homogeneous array; all elements share the same dtype.
4. How do you create an array from a Python list?

Answer: Use `np.array([1,2,3])`.
5. How to check the shape of an array?

Answer: Use `.shape` attribute, e.g., `arr.shape`.
6. What is `dtype`?

Answer: The data type of array elements, e.g., `np.int32`, `np.float64`.
7. How to get the number of dimensions?

Answer: Use `.ndim`.
8. What does `np.zeros((3,4))` do?

Answer: Creates a 3x4 array filled with zeros.
9. Why use NumPy over lists for numeric work?

Answer: Speed, memory efficiency, and vectorized operations.
10. How do you find the total number of elements?

Answer: Use `.size`.

## Interview Questions — Intermediate (10) with Answers

1. Explain broadcasting in NumPy.

Answer: Broadcasting lets NumPy perform arithmetic on arrays with different shapes by expanding the smaller array across the larger one following specific rules.

2. What is the difference between `ravel()` and `flatten()`?

Answer: `ravel()` returns a view when possible (no copy), `flatten()` always returns a copy.

3. How to check memory usage of an array?

Answer: Use `.nbytes` for total bytes, `.itemsize` for per-element size.

4. When does NumPy upcast dtypes?

Answer: When combining arrays with different dtypes, NumPy promotes to a common dtype that can represent all values (e.g., int + float -> float).

5. How to create an identity matrix?

Answer: Use `np.eye(n)` or `np.identity(n)`.

6. What are views and copies?

Answer: A view is a new array object that looks at the same data (no data copy). A copy duplicates the data.

7. How to save and load arrays?

Answer: Use `np.save('file.npy', arr)` and `np.load('file.npy')`.

8. Explain `astype()` method.

Answer: `arr.astype(new_dtype)` returns a copy of the array cast to `new_dtype`.

9. What is `np.arange()` vs `np.linspace()`?

Answer: `arange()` uses a step to generate values; `linspace()` generates a specified number of evenly spaced samples between start and stop.

10. How to handle NaNs in NumPy arrays?

Answer: Use `np.isnan()` to detect, and `np.nanmean`, `np.nanstd` functions for statistics that ignore NaN.

## Interview Questions — Advanced (10) with Answers

1. Explain memory layout (C vs Fortran order).

Answer: C-order stores rows contiguously (row-major), Fortran-order stores columns contiguously (column-major). Memory layout affects slicing, transposes, and performance.
2. How does NumPy broadcasting decide compatibility?

Answer: Compare shapes from trailing dimensions; dimensions are compatible if equal or one of them is 1.
3. What is `np.einsum` and when to use it?

Answer: `einsum` provides Einstein summation notation for powerful, often more efficient multi-dimensional reductions and contractions.
4. How to avoid copying data unnecessarily?

Answer: Use views, slice operations, and functions like `np.ravel()` (which may return view), and avoid `astype()` unless necessary.
5. Describe how to use memory-mapped files with NumPy.

Answer: Use `np.memmap` to work with arrays stored on disk as if they were in memory, enabling out-of-core processing.
6. How to optimize large array computations?

Answer: Use vectorized operations, chunking, memory layout tuning (C vs F), and consider using libraries like Numba for JIT compilation or Dask for distributed arrays.
7. Explain structured arrays and use cases.

Answer: Structured arrays have fields with names and different dtypes, useful for heterogeneous tabular data with NumPy-level performance.
8. When does a slice return a view vs a copy?

Answer: Slices generally return views, but not always (e.g., non-contiguous steps or fancy indexing produce copies).
9. What are some pitfalls of floating-point arithmetic in NumPy?

Answer: Floating point precision errors, representation limits, and NaNs/Infs; use appropriate dtypes and numeric stability techniques.
10. How to implement broadcasting manually for two arrays?

Answer: Expand the smaller array using `np.reshape` and `np.repeat` or `np.broadcast_to` to match the larger array's shape before performing element-wise ops.

## Practice Problems

### Easy (5)
1. Create a NumPy array from a list of integers and print its dtype and shape.
2. Create a 3x3 zero matrix and set the diagonal to 1.
3. Generate an array of numbers from 0 to 9 and print the even numbers.
4. Compute the mean of `[1,2,3,4,5]` using NumPy.
5. Create an array of 10 ones with dtype `float32`.

### Medium (5)
1. Given a 1-D array of length 12, reshape it to 3x4 and compute the sum along axis 0.
2. Create two arrays and demonstrate broadcasting for addition.
3. Given an array with NaNs, compute the mean ignoring NaNs.
4. Multiply a 2x3 and a 3x2 matrix and verify the result.
5. Save an array to disk and load it back.

### Hard (5)
1. Implement a function using NumPy that computes the pairwise Euclidean distance matrix for an (n x d) dataset without explicit Python loops.
2. Given a large array that doesn't fit in memory, outline how to process it in chunks and compute the global mean.
3. Use broadcasting to compute a matrix where `M[i,j] = (i - j)**2` for i,j in range(1000) efficiently.
4. Demonstrate how to use `np.memmap` to read a large binary array and compute its column means.
5. Build a small feature normalization pipeline that handles NaNs and scales features to zero mean and unit variance.

Note: Solutions for practice problems are available in the dedicated practice notebook `_023_numpy_practice_problems.ipynb` (no answers there).

## Chapter Summary and Cheat Sheet

- `import numpy as np` — standard import
- `np.array(...)` — create arrays
- `.shape`, `.dtype`, `.ndim`, `.size`, `.nbytes` — inspect arrays
- Use vectorized functions (`np.sqrt`, `np.add`, etc.) for performance
- Use `np.save`/`np.load` for quick binary persistence

Keep practicing: understanding `ndarray` fundamentals makes the rest of NumPy easier.