# NumPy Array Creation (Chapter 2)

This chapter covers the foundational NumPy array creation functions students need for data analytics, scientific computing, machine learning and interview preparation. Every function is explained in detail with real-world examples, common pitfalls, and advanced usage.

## Learning Objectives

After completing this chapter, you will be able to:

- Create NumPy arrays using constructors and factory functions
- Understand when to use `np.array`, `np.asarray`, `np.fromiter`, and `np.frombuffer`
- Generate arrays of zeros, ones, empty values, and constant values
- Create identity matrices, ranges, and logarithmic sequences
- Choose the best array creation method for performance and data type control
- Identify common errors and troubleshooting strategies

## Introduction

NumPy array creation functions are the first step for any numerical workflow. Whether you are preparing dataset inputs, initializing weights for machine learning models, or generating test data, NumPy provides flexible constructors that cover every use case. This chapter starts from zero and builds up to advanced array creation techniques.

## Why Array Creation Matters

Efficient array creation reduces bugs, improves performance, and enables reproducible data pipelines. Creating arrays correctly also ensures that operations are vectorized, memory-managed, and compatible with the NumPy ecosystem.

# 1. np.array()

## Definition

`np.array()` constructs a new NumPy `ndarray` from an arbitrary Python sequence, nested sequences, or an existing array-like structure. It is the most common starting point for turning Python data into NumPy arrays.

## Purpose

Use `np.array()` when you want to create a new array from Python lists, tuples, or other array-like objects and have full control over data type, memory layout, and dimensionality.

## Real-world Use Cases

- Converting tabular input data into a numeric array for statistical analysis
- Preparing image pixel values for machine learning models
- Building feature matrices from nested lists in data preprocessing
- Converting experimental measurements from Python lists to numeric arrays

## Syntax

`np.array(object, dtype=None, copy=True, order='K', subok=False, ndmin=0)`

## Parameters

| Parameter | Type | Default | Description |
| --- | --- | --- | --- |
| `object` | array-like | required | Input data to convert into an ndarray. Can be a list, tuple, nested sequence, or other array-like object. |
| `dtype` | data-type or None | None | Desired data type for the output array. If None, NumPy infers the data type from the input. |
| `copy` | bool | True | If True, a new array is always created. If False and `object` is already an ndarray, a view may be returned when possible. |
| `order` | {'C', 'F', 'A', 'K'} | 'K' | Memory layout order: row-major ('C'), column-major ('F'), any ('A'), or preserve input order if possible ('K'). |
| `subok` | bool | False | If True, subclasses of ndarray are preserved. If False, returns a base-class ndarray. |
| `ndmin` | int | 0 | Minimum number of dimensions for the output array. Pads with ones on the left if needed. |

### Parameter details

- `object`: Accepts nested Python sequences or any array-like object. A scalar is also valid and becomes a zero-dimensional array unless `ndmin` is specified.
- `dtype`: Common values include `np.int64`, `np.float32`, `np.bool_`, and `np.str_`. If the requested type cannot represent the data, NumPy raises a `TypeError` or performs conversion with possible loss of precision.
- `copy`: Use `copy=False` when you want to avoid unnecessary memory allocation for existing arrays. Use `copy=True` when you need a guaranteed independent array.
- `order`: `'C'` means C-style row-major layout, `'F'` means Fortran-style column-major layout, `'A'` means any layout and `'K'` means preserve the input layout if possible.
- `subok`: If you pass a subclass like `np.matrix`, `subok=True` will preserve the subclass. Otherwise NumPy returns an `ndarray`.
- `ndmin`: Useful when you need to ensure a minimum rank for broadcasting or matrix operations. For example, `np.array([1, 2], ndmin=2)` returns shape `(1, 2)`.

## Return Value

- Returns: `numpy.ndarray`
- Shape: depends on the input and `ndmin` value
- Dtype: determined by `dtype` or inferred from input data
- Memory: allocates a new array by default; `copy=False` may avoid allocation for existing arrays.

## Notes

- `np.array()` performs a deep copy by default, so it is safe for independent data manipulation.
- When converting nested lists with inconsistent lengths, NumPy creates an array of Python objects, which is usually slower.

## Warnings

- Avoid `np.array()` for extremely large datasets if you already have an ndarray or memory buffer, because `np.asarray()` can be more efficient.
- Be careful with `dtype='int'` on mixed numeric input; floats will be truncated.

## Common Errors

- `ValueError: setting an array element with a sequence.` when nested sequences have different lengths.
- `TypeError` when requested dtype is incompatible with the input.

## Related Functions

- `np.asarray()`
- `np.fromiter()`
- `np.frombuffer()`
- `np.zeros()`

In [1]:
# Import NumPy using the standard alias
import numpy as np

# Create a one-dimensional integer array from a Python list
measurements = [10, 15, 20, 25]
array_from_list = np.array(measurements, dtype=np.int64)
print('array_from_list:', array_from_list)
print('shape:', array_from_list.shape)
print('dtype:', array_from_list.dtype)

# Create a two-dimensional array from nested lists
matrix_data = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
matrix_array = np.array(matrix_data, dtype=np.float64, ndmin=2)
print('matrix_array:', matrix_array)
print('shape:', matrix_array.shape)

# Use copy=False when the input is already an ndarray to avoid an extra allocation
original = np.array([1.5, 2.5, 3.5])
no_copy_array = np.array(original, copy=False)
print('original is no_copy_array:', original is no_copy_array)
print('original base:', original.base)

array_from_list: [10 15 20 25]
shape: (4,)
dtype: int64
matrix_array: [[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
shape: (3, 3)
original is no_copy_array: True
original base: None


### Advanced Example

Use `ndmin` and `order` to control shape and memory layout when preparing data for linear algebra or signal processing.

In [2]:
# Create a row vector with at least 2 dimensions and Fortran-order memory layout
row_vector = np.array([1, 2, 3], dtype=np.float32, ndmin=2, order='F')
print('row_vector shape:', row_vector.shape)
print('row_vector flags:', row_vector.flags)

# Demonstrate how object arrays are created when nested sequence lengths differ
ragged = np.array([[1, 2], [3, 4, 5]], dtype=object)
print('ragged array:', ragged)
print('ragged dtype:', ragged.dtype)

row_vector shape: (1, 3)
row_vector flags:   C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : False
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False

ragged array: [list([1, 2]) list([3, 4, 5])]
ragged dtype: object


# 2. np.asarray()

## Definition

`np.asarray()` converts its input to a NumPy array, but avoids copying data when the input is already an ndarray with a compatible dtype and order.

## Purpose

Use `np.asarray()` when you want to convert array-like data into an ndarray while preserving memory and avoiding unnecessary copy overhead.

## Real-world Use Cases

- Wrapping input arrays before applying vectorized functions in a machine learning pipeline
- Converting pandas Series or DataFrames to NumPy arrays for model training
- Accepting callbacks that may provide either a list or an ndarray and normalizing them to ndarray.

## Syntax

`np.asarray(a, dtype=None, order=None)`

## Parameters

| Parameter | Type | Default | Description |
| --- | --- | --- | --- |
| `a` | array-like | required | Input data to convert to an ndarray. |
| `dtype` | data-type or None | None | Desired output data type. If None, NumPy preserves the input dtype when possible. |
| `order` | {'C', 'F', 'A', 'K'} or None | None | Memory layout of the output array. If None, preserves the input order where possible. |

## Return Value

- Returns: `numpy.ndarray`
- Shape: same as input if possible
- Dtype: either preserved or converted to the requested type
- Memory: avoids copy when the input is already a compatible ndarray.

## Notes

- `np.asarray()` does not guarantee a copy; the returned object may share memory with the input.
- For Python lists and tuples, it still creates a new ndarray.

## Warnings

- Do not modify the returned array if the original input must remain unchanged and the input was already an ndarray.

## Common Errors

- `TypeError` when the input cannot be converted to a NumPy array.

## Related Functions

- `np.array()`
- `np.asarray_chkfinite()`
- `np.asanyarray()`

In [2]:
import numpy as np
# Convert a Python list to ndarray with minimal overhead
list_data = [100, 200, 300]
ndarray_from_list = np.asarray(list_data, dtype=np.int32)
print('ndarray_from_list:', ndarray_from_list)
print('dtype:', ndarray_from_list.dtype)

# When the input is already an ndarray, np.asarray may reuse memory
existing_array = np.array([1.0, 2.0, 3.0])
alias_array = np.asarray(existing_array)
print('existing_array is alias_array:', existing_array is alias_array)

# Convert from a pandas Series or other array-like object (example only)
# Note: import pandas only if needed in a real workflow
# from pandas import Series
# series = Series([5, 6, 7])
# ndarray_from_series = np.asarray(series)
# print('ndarray_from_series:', ndarray_from_series)

ndarray_from_list: [100 200 300]
dtype: int32
existing_array is alias_array: True


# 3. np.fromiter()

## Definition

`np.fromiter()` creates a one-dimensional ndarray from any iterable object, reading values lazily and allocating the target array directly.

## Purpose

Use `np.fromiter()` when you have a Python iterator or generator and need a fast way to convert its values into a NumPy array.

## Real-world Use Cases

- Reading a large stream of numeric measurements from a generator into an ndarray
- Converting a CSV parser or file iterator into array data without creating an intermediate list
- Building feature arrays from on-the-fly computations in machine learning preprocessing.

## Syntax

`np.fromiter(iterable, dtype=float, count=-1)`

## Parameters

| Parameter | Type | Default | Description |
| --- | --- | --- | --- |
| `iterable` | iterable | required | A Python iterable or iterator yielding numeric values. |
| `dtype` | data-type | float | Desired data type of the output array. |
| `count` | int | -1 | Number of items to read from the iterable. `-1` means read until the iterable is exhausted. |

## Parameter details

- `iterable`: Must yield items compatible with the requested `dtype`; for example, integers, floats or booleans.
- `dtype`: Use `np.float64` for high-precision scientific data or `np.int32` for integer sequences.
- `count`: When the size of the iterable is known, pass it to avoid extra overhead; otherwise use `-1`.

## Return Value

- Returns: `numpy.ndarray` of shape `(count,)` if `count` is non-negative, otherwise the length of the iterable.
- Dtype: requested dtype.
- Memory: allocates a contiguous one-dimensional array directly, which makes it efficient for large iterables.

## Notes

- `np.fromiter()` always returns a 1-D array, even if the iterable contains tuples or higher rank values.

## Warnings

- If `count` is too large, NumPy will pad the result with zeros. If `count` is too small, data is truncated.

## Common Errors

- `TypeError` when iterable items cannot be converted to the requested dtype.
- `ValueError` when the iterable yields non-scalar values for a scalar dtype.

## Related Functions

- `np.frombuffer()`
- `np.array()`
- `np.asarray()`

In [3]:
# Use a generator expression to lazily produce values
def square_generator(n):
    for value in range(n):
        yield value * value

# Create a NumPy array directly from the iterator
squared_values = np.fromiter(square_generator(10), dtype=np.int64, count=10)
print('squared_values:', squared_values)
print('shape:', squared_values.shape)

# Create an array from a list iterator without making a temporary list
input_numbers = [2, 4, 6, 8]
even_array = np.fromiter(iter(input_numbers), dtype=np.int64)
print('even_array:', even_array)

squared_values: [ 0  1  4  9 16 25 36 49 64 81]
shape: (10,)
even_array: [2 4 6 8]


# 4. np.frombuffer()

## Definition

`np.frombuffer()` creates a one-dimensional ndarray that uses an existing buffer object as its data source without copying it.

## Purpose

Use `np.frombuffer()` when working with binary data, memory-mapped files, or byte buffers and you want to interpret raw bytes as a NumPy array.

## Real-world Use Cases

- Reading binary sensor data from a buffer into a numeric array.
- Converting raw bytes returned by a network socket into a NumPy array for signal processing.
- Working with memoryviews, bytearrays, or shared memory without copying data.

## Syntax

`np.frombuffer(buffer, dtype=float, count=-1, offset=0)`

## Parameters

| Parameter | Type | Default | Description |
| --- | --- | --- | --- |
| `buffer` | buffer-like | required | Object exposing the buffer interface, such as `bytes`, `bytearray`, or `memoryview`. |
| `dtype` | data-type | float | Data type used to interpret the buffer contents. |
| `count` | int | -1 | Number of items to read from the buffer. `-1` reads until the end. |
| `offset` | int | 0 | Start position in bytes within the buffer. |

## Parameter details

- `buffer`: Must support the buffer protocol. Immutable `bytes` objects are allowed, but the resulting array is read-only.
- `dtype`: Choose the correct byte interpretation. For example, `np.uint8` for raw bytes or `np.int16` for signed 16-bit samples.
- `count`: Helps control array length. If `count` is set and the buffer does not contain enough values, a `ValueError` is raised.
- `offset`: Useful when the buffer contains a header or metadata before the numeric payload.

## Return Value

- Returns: `numpy.ndarray`
- Shape: one-dimensional
- Dtype: as requested
- Memory: no copy, shares the underlying buffer when possible.

## Notes

- `np.frombuffer()` returns a read-only array for immutable buffers like `bytes`.
- When using writable buffers, modifications to the array may affect the original buffer.

## Warnings

- Be careful with endianness and byte order. The buffer is interpreted according to the requested dtype.

## Common Errors

- `ValueError` when the buffer length is not compatible with the requested dtype and count.
- `TypeError` when the object does not support the buffer protocol.

## Related Functions

- `np.fromfile()`
- `np.ndarray()`
- `np.memmap()`

In [4]:
# Create a bytes buffer that contains four 16-bit unsigned integers
raw_bytes = bytearray([1, 0, 2, 0, 3, 0, 4, 0])
# Interpret the byte buffer as uint16 values
uint16_array = np.frombuffer(raw_bytes, dtype=np.uint16)
print('uint16_array:', uint16_array)
print('dtype:', uint16_array.dtype)

# Create a memoryview and interpret the same bytes as signed 16-bit integers
signed_view = memoryview(raw_bytes)
int16_array = np.frombuffer(signed_view, dtype=np.int16)
print('int16_array:', int16_array)

uint16_array: [1 2 3 4]
dtype: uint16
int16_array: [1 2 3 4]


# 5. np.zeros()

## Definition

`np.zeros()` creates a new array filled with zeros. It is ideal for initializing model weights, masks, and placeholder arrays.

## Purpose

Use `np.zeros()` when you need a numeric array initialized to zero with a specified shape and dtype.

## Real-world Use Cases

- Creating bias vectors for neural network layers.
- Allocating an output array before filling it with computed values.
- Initializing zero masks for missing data handling.

## Syntax

`np.zeros(shape, dtype=float, order='C')`

## Parameters

| Parameter | Type | Default | Description |
| --- | --- | --- | --- |
| `shape` | int or tuple of ints | required | Shape of the new array. Use a tuple for multi-dimensional arrays. |
| `dtype` | data-type | float | Desired data type of the array. |
| `order` | {'C', 'F'} | 'C' | Memory layout order: row-major ('C') or column-major ('F'). |

## Notes

- `np.zeros()` always creates a new array.
- For integer arrays, zeros are exact; for floats, zeros may still have a floating-point dtype.

## Common Errors

- `TypeError` if `shape` is not an integer or tuple of integers.
- `ValueError` if negative values are included in the shape.

## Related Functions

- `np.ones()`
- `np.full()`
- `np.empty()`

In [5]:
# Initialize a 3x3 float matrix of zeros
zero_matrix = np.zeros((3, 3), dtype=np.float64)
print('zero_matrix:', zero_matrix)
print('shape:', zero_matrix.shape)

# Create a one-dimensional integer zero array for counts
zero_counts = np.zeros(5, dtype=np.int32)
print('zero_counts:', zero_counts)

zero_matrix: [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
shape: (3, 3)
zero_counts: [0 0 0 0 0]


# 6. np.zeros_like()

## Definition

`np.zeros_like()` creates a new array of zeros with the same shape and dtype as an existing array.

## Purpose

Use `np.zeros_like()` when you need a zero-initialized array that matches the shape and dtype of an existing array, without explicitly repeating its dimensions.

## Real-world Use Cases

- Creating a mask array for an existing dataset.
- Preparing a zero-valued array to store computed residuals.
- Initializing gradients that match model parameter shapes in deep learning code.

## Syntax

`np.zeros_like(a, dtype=None, order='K', subok=True, shape=None)`

## Parameters

| Parameter | Type | Default | Description |
| --- | --- | --- | --- |
| `a` | array-like | required | Reference array whose shape and dtype are used. |
| `dtype` | data-type or None | None | Desired output dtype. If None, uses `a.dtype`. |
| `order` | {'C', 'F', 'K'} | 'K' | Memory layout of the output. 'K' preserves input order when possible. |
| `subok` | bool | True | If True, preserves subclasses of `a`. |
| `shape` | tuple of ints or None | None | If provided, overrides the output shape. |

## Notes

- If `shape` is provided, the output shape can differ from `a` but must be compatible with its size.

## Common Errors

- `TypeError` if `shape` is not a tuple of ints.
- `ValueError` if the requested `shape` and dtype size mismatch the original size.

In [6]:
# Create a reference array and then a zero array with matching shape and dtype
reference_array = np.ones((2, 4), dtype=np.float32)
matched_zeros = np.zeros_like(reference_array)
print('matched_zeros:', matched_zeros)
print('shape:', matched_zeros.shape, 'dtype:', matched_zeros.dtype)

# Override the dtype while keeping the same shape
matched_zeros_int = np.zeros_like(reference_array, dtype=np.int16)
print('matched_zeros_int dtype:', matched_zeros_int.dtype)

matched_zeros: [[0. 0. 0. 0.]
 [0. 0. 0. 0.]]
shape: (2, 4) dtype: float32
matched_zeros_int dtype: int16


# 7. np.ones()

## Definition

`np.ones()` creates an array filled with ones. It is commonly used for initializing coefficient arrays and bias terms.

## Purpose

Use `np.ones()` whenever you need an array with all values initialized to one and specific shape and dtype.

## Real-world Use Cases

- Preparing a bias vector for a linear regression model.
- Initializing weights in a simple neural network before scaling or applying regularization.
- Creating a fallback array for multiplicative masks.

## Syntax

`np.ones(shape, dtype=None, order='C')`

## Parameters

| Parameter | Type | Default | Description |
| --- | --- | --- | --- |
| `shape` | int or tuple of ints | required | Shape of the result array. |
| `dtype` | data-type or None | None | Desired dtype for the array. |
| `order` | {'C', 'F'} | 'C' | Memory layout order. |

## Notes

- `np.ones()` always returns a fresh array and does not share memory with any input.

## Common Errors

- `TypeError` if `shape` is invalid.
- `ValueError` if `shape` contains negative values.

In [7]:
# Create a 2x5 array of ones for a bias vector or mask
bias_array = np.ones((2, 5), dtype=np.float64)
print('bias_array:', bias_array)

# Use ones_like to create a matching ones array from an existing array
data_array = np.array([[1, 2], [3, 4]])
ones_matching = np.ones_like(data_array, dtype=np.float32)
print('ones_matching:', ones_matching)

bias_array: [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
ones_matching: [[1. 1.]
 [1. 1.]]


# 8. np.ones_like()

## Definition

`np.ones_like()` creates a new array of ones with the same shape and dtype as an existing array.

## Purpose

Use this function when you want to quickly create a `1`-filled array that matches another array's shape and dtype without repeating its dimensions.

## Syntax

`np.ones_like(a, dtype=None, order='K', subok=True, shape=None)`

## Parameters

| Parameter | Type | Default | Description |
| --- | --- | --- | --- |
| `a` | array-like | required | Reference array. |
| `dtype` | data-type or None | None | Desired dtype for the result. |
| `order` | {'C', 'F', 'K'} | 'K' | Memory order for the returned array. |
| `subok` | bool | True | Preserve subclasses of `a` if True. |
| `shape` | tuple of ints or None | None | Override the output shape if needed. |

## Notes

- Matching `dtype` and shape avoids incompatibility errors later in pipelines.

In [8]:
# Create an existing array and then an array of ones with the same shape
existing_matrix = np.array([[0, 1, 2], [3, 4, 5]], dtype=np.int16)
ones_like_existing = np.ones_like(existing_matrix)
print('ones_like_existing:', ones_like_existing)
print('dtype:', ones_like_existing.dtype)

# Override the dtype when creating the ones-like array
ones_like_float = np.ones_like(existing_matrix, dtype=np.float64)
print('ones_like_float dtype:', ones_like_float.dtype)

ones_like_existing: [[1 1 1]
 [1 1 1]]
dtype: int16
ones_like_float dtype: float64


# 9. np.empty()

## Definition

`np.empty()` allocates a new array without initializing its entries. The contents are arbitrary and should be overwritten before use.

## Purpose

Use `np.empty()` when you need to allocate space for an array and plan to fill it immediately, because it is faster than initializing with zeros or ones.

## Real-world Use Cases

- Reserving memory for a large matrix before computing its values.
- Allocating an output array in a numerical algorithm where every element will be assigned.
- Pre-allocating arrays in a performance-critical loop.

## Syntax

`np.empty(shape, dtype=float, order='C')`

## Parameters

| Parameter | Type | Default | Description |
| --- | --- | --- | --- |
| `shape` | int or tuple of ints | required | Shape of the uninitialized array. |
| `dtype` | data-type | float | Desired dtype of the array. |
| `order` | {'C', 'F'} | 'C' | Memory layout of the result. |

## Notes

- The values in `np.empty()` arrays are indeterminate and should not be used before assignment.

## Warnings

- Never assume `np.empty()` returns zeros. The array may contain arbitrary data from memory.

## Common Errors

- Using the output without initializing it first, which can lead to unpredictable results.

## Related Functions

- `np.zeros()`
- `np.ones()`
- `np.full()`

In [9]:
# Allocate a large array for future computation
buffer_array = np.empty((2, 3), dtype=np.float64)
print('buffer_array before initialization:', buffer_array)

# Fill the allocated array with computed values
for row_index in range(buffer_array.shape[0]):
    for col_index in range(buffer_array.shape[1]):
        buffer_array[row_index, col_index] = row_index * 10 + col_index

print('buffer_array after fill:', buffer_array)

buffer_array before initialization: [[0. 0. 0.]
 [0. 0. 0.]]
buffer_array after fill: [[ 0.  1.  2.]
 [10. 11. 12.]]


# 10. np.empty_like()

## Definition

`np.empty_like()` creates an uninitialized array with the same shape and dtype as another array.

## Purpose

Use `np.empty_like()` to allocate output arrays that match an existing array without initializing entries, for maximum speed.

## Syntax

`np.empty_like(prototype, dtype=None, order='K', subok=True, shape=None)`

## Parameters

| Parameter | Type | Default | Description |
| --- | --- | --- | --- |
| `prototype` | array-like | required | Array whose shape and dtype are used as a template. |
| `dtype` | data-type or None | None | Desired dtype for result. |
| `order` | {'C', 'F', 'K'} | 'K' | Output memory layout. |
| `subok` | bool | True | Preserve subclasses if True. |
| `shape` | tuple of ints or None | None | Override the output shape. |

## Notes

- The array content is undefined until you assign values.

In [10]:
# Create a prototype array and then allocate a matching empty output array
example_matrix = np.array([[1, 2, 3], [4, 5, 6]], dtype=np.int32)
temporary_result = np.empty_like(example_matrix)
print('temporary_result before init:', temporary_result)

# Fill values before using the array
temporary_result[:] = example_matrix * 2
print('temporary_result after fill:', temporary_result)

temporary_result before init: [[  5701633  40108121 159254909]
 [ 40112494 159254909     65911]]
temporary_result after fill: [[ 2  4  6]
 [ 8 10 12]]


# 11. np.full()

## Definition

`np.full()` creates a new array filled with a specified scalar value.

## Purpose

Use `np.full()` when you need an array initialized to a constant other than zero or one.

## Real-world Use Cases

- Defining an initial fill value for missing data imputation.
- Setting a weight matrix to a constant before applying a scaling factor.
- Creating a constant-valued feature array for model offsets.

## Syntax

`np.full(shape, fill_value, dtype=None, order='C')`

## Parameters

| Parameter | Type | Default | Description |
| --- | --- | --- | --- |
| `shape` | int or tuple of ints | required | Desired output shape. |
| `fill_value` | scalar | required | Constant value to fill the array. |
| `dtype` | data-type or None | None | Desired dtype of the output array. |
| `order` | {'C', 'F'} | 'C' | Memory order of the output. |

## Notes

- The fill value is broadcast to every element in the output array.

In [11]:
# Create a 4x4 matrix filled with a constant value for initialization
constant_matrix = np.full((4, 4), fill_value=7, dtype=np.int16)
print('constant_matrix:', constant_matrix)

# Use a float fill value for feature scaling
scaled_offset = np.full(5, fill_value=0.1, dtype=np.float64)
print('scaled_offset:', scaled_offset)

constant_matrix: [[7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]]
scaled_offset: [0.1 0.1 0.1 0.1 0.1]


# 12. np.full_like()

## Definition

`np.full_like()` creates a new array with the same shape and dtype as an existing array, filled with a specified scalar.

## Purpose

Use `np.full_like()` to create constant arrays that match the shape of another array without manually copying dimensions.

## Syntax

`np.full_like(a, fill_value, dtype=None, order='K', subok=True, shape=None)`

## Parameters

| Parameter | Type | Default | Description |
| --- | --- | --- | --- |
| `a` | array-like | required | Array whose shape/dtype are used for the result. |
| `fill_value` | scalar | required | The constant used to fill the array. |
| `dtype` | data-type or None | None | Output dtype, if overriding the input dtype. |
| `order` | {'C', 'F', 'K'} | 'K' | Memory order for returned array. |
| `subok` | bool | True | Preserve subclass if True. |
| `shape` | tuple of ints or None | None | Override output shape if needed. |

## Notes

- This function is useful when you want constant arrays that align with existing data shapes.

In [ ]:
# Create a constant array that matches an existing dataset's shape
dataset = np.random.rand(3, 2)
constant_weights = np.full_like(dataset, fill_value=0.5)
print('dataset shape:', dataset.shape)
print('constant_weights:', constant_weights)

# 13. np.eye()

## Definition

`np.eye()` creates a 2-D identity matrix with ones on the diagonal and zeros elsewhere.

## Purpose

Use `np.eye()` when you need an identity matrix for linear algebra, initialization, or transforming coordinates.

## Real-world Use Cases

- Constructing identity matrices for matrix inversion and eigenvalue computations.
- Creating basis vectors for projection operations.
- Initializing an identity layer in simple neural network models.

## Syntax

`np.eye(N, M=None, k=0, dtype=float, order='C')`

## Parameters

| Parameter | Type | Default | Description |
| --- | --- | --- | --- |
| `N` | int | required | Number of rows in the output matrix. |
| `M` | int or None | None | Number of columns. If None, uses `N` (square matrix). |
| `k` | int | 0 | Index of the diagonal: 0 for main diagonal, positive for above, negative for below. |
| `dtype` | data-type | float | Desired dtype of the output matrix. |
| `order` | {'C', 'F'} | 'C' | Memory layout order. |

## Notes

- `np.eye(3)` creates a 3x3 identity matrix.
- For non-square matrices, `k` controls which diagonal receives the ones.

## Common Errors

- `TypeError` if `N` or `M` is not an integer.

In [12]:
# Create a 4x4 identity matrix
identity_matrix = np.eye(4, dtype=np.float64)
print('identity_matrix:', identity_matrix)

# Create a rectangular matrix with ones one diagonal above the main diagonal
rectangular_eye = np.eye(3, 5, k=1, dtype=np.int32)
print('rectangular_eye:', rectangular_eye)

identity_matrix: [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
rectangular_eye: [[0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]]


# 14. np.identity()

## Definition

`np.identity()` returns a square identity matrix with ones on the main diagonal and zeros elsewhere.

## Purpose

Use `np.identity()` when you need a square identity matrix and prefer a function name that emphasizes the square nature.

## Syntax

`np.identity(n, dtype=None)`

## Parameters

| Parameter | Type | Default | Description |
| --- | --- | --- | --- |
| `n` | int | required | Number of rows and columns for the square identity matrix. |
| `dtype` | data-type or None | None | Desired dtype for the output matrix. |

## Notes

- Equivalent to `np.eye(n, dtype=dtype)` for square matrices.

## Common Errors

- `TypeError` if `n` is not an integer.

In [3]:
# Create a 5x5 square identity matrix
square_identity = np.identity(5, dtype=np.float32)
print('square_identity:', square_identity)

square_identity: [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


# 15. np.arange()

## Definition

`np.arange()` returns evenly spaced values within a half-open interval `[start, stop)` using a specified step.

## Purpose

Use `np.arange()` to generate sequences of numbers for loops, indexing, axes, or temporal grids.

## Real-world Use Cases

- Generating time steps for simulations.
- Creating index arrays for slicing and plotting.
- Building training sample indices for batch processing.

## Syntax

`np.arange([start,] stop[, step,], dtype=None)`

## Parameters

| Parameter | Type | Default | Description |
| --- | --- | --- | --- |
| `start` | scalar | 0 | Start of interval. |
| `stop` | scalar | required | End of interval (exclusive). |
| `step` | scalar | 1 | Spacing between values. |
| `dtype` | data-type or None | None | Desired dtype of the output array. |

## Notes

- The output includes `start` and excludes `stop`.
- For floating-point `step`, rounding issues may occur.

## Warnings

- Avoid `np.arange()` with non-integer steps when precise endpoint values are required; use `np.linspace()` instead.

## Common Errors

- `TypeError` if arguments are not scalar values.
- `ValueError` if step is zero.

## Related Functions

- `np.linspace()`
- `np.logspace()`
- `np.geomspace()`

In [4]:
# Generate a simple integer range from 0 to 9
range_array = np.arange(10)
print('range_array:', range_array)

# Create a range with a custom start and step
custom_range = np.arange(2, 11, 2)
print('custom_range:', custom_range)

# Create a floating-point array from 0 to 1 with step 0.2
float_range = np.arange(0.0, 1.0, 0.2, dtype=np.float64)
print('float_range:', float_range)

range_array: [0 1 2 3 4 5 6 7 8 9]
custom_range: [ 2  4  6  8 10]
float_range: [0.  0.2 0.4 0.6 0.8]


# 16. np.linspace()

## Definition

`np.linspace()` returns evenly spaced values over a closed interval `[start, stop]`.

## Purpose

Use `np.linspace()` when you need a specific number of samples with a guaranteed endpoint, such as for plotting or interpolation.

## Real-world Use Cases

- Generating x-coordinates for smooth line plots.
- Creating sample points for interpolation and numerical integration.
- Defining training schedules or regularization curves.

## Syntax

`np.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None, axis=0)`

## Parameters

| Parameter | Type | Default | Description |
| --- | --- | --- | --- |
| `start` | scalar | required | Starting value of the sequence. |
| `stop` | scalar | required | End value of the sequence. |
| `num` | int | 50 | Number of samples to generate. |
| `endpoint` | bool | True | If True, include `stop` in the output. |
| `retstep` | bool | False | If True, return the step size as well as the samples. |
| `dtype` | data-type or None | None | Desired dtype of the output. |
| `axis` | int | 0 | Axis in the result to store the samples. |

## Parameter details

- `num`: Use a higher value for higher resolution when sampling continuous functions.
- `endpoint`: Set to False if you want the stop value excluded.
- `retstep`: Useful when you need to know the spacing between generated values.
- `axis`: Controls which axis the samples vary along for multi-dimensional output.

## Return Value

- Returns: `numpy.ndarray` or tuple `(samples, step)` if `retstep=True`.
- Shape: `(num,)` by default.
- Dtype: requested dtype or inferred from inputs.

## Notes

- `np.linspace()` is more reliable than `np.arange()` for floating-point sequences because it avoids cumulative rounding errors.

## Common Errors

- `TypeError` if `num` or `axis` is not an integer.
- `ValueError` if `num` is negative.

In [5]:
# Generate 5 evenly spaced values between 0 and 1 inclusive
linear_samples, spacing = np.linspace(0.0, 1.0, num=5, endpoint=True, retstep=True)
print('linear_samples:', linear_samples)
print('spacing:', spacing)

# Use linspace for a smooth plot axis
plot_points = np.linspace(-2.0, 2.0, num=9, dtype=np.float32)
print('plot_points:', plot_points)

linear_samples: [0.   0.25 0.5  0.75 1.  ]
spacing: 0.25
plot_points: [-2.  -1.5 -1.  -0.5  0.   0.5  1.   1.5  2. ]


# 17. np.logspace()

## Definition

`np.logspace()` generates numbers spaced evenly on a log scale between powers of 10.

## Purpose

Use `np.logspace()` when modeling exponential growth, logarithmic axes, or when you need samples between decades.

## Real-world Use Cases

- Generating learning rate schedules for machine learning.
- Creating frequency bins for signal processing.
- Designing logarithmic plots for scientific data.

## Syntax

`np.logspace(start, stop, num=50, endpoint=True, base=10.0, dtype=None, axis=0)`

## Parameters

| Parameter | Type | Default | Description |
| --- | --- | --- | --- |
| `start` | scalar | required | Starting exponent. Output begins at `base**start`. |
| `stop` | scalar | required | Ending exponent. Output ends at `base**stop` if `endpoint=True`. |
| `num` | int | 50 | Number of samples. |
| `endpoint` | bool | True | If True, include `base**stop`. |
| `base` | float | 10.0 | Base of the log scale. |
| `dtype` | data-type or None | None | Desired dtype of the output. |
| `axis` | int | 0 | Axis to store the samples in the result. |

## Notes

- Use `np.logspace()` for values spanning multiple orders of magnitude.

## Common Errors

- `TypeError` if `num` is not an integer.
- `ValueError` if `num` is negative.

In [6]:
# Generate logarithmically spaced values from 10^0 to 10^3
log_samples = np.logspace(0, 3, num=4, endpoint=True, base=10.0, dtype=np.float64)
print('log_samples:', log_samples)

# Create a logspace array with a non-standard base for custom scaling
custom_log_samples = np.logspace(1, 4, num=4, base=2.0, dtype=np.float64)
print('custom_log_samples:', custom_log_samples)

log_samples: [   1.   10.  100. 1000.]
custom_log_samples: [ 2.  4.  8. 16.]


# 18. np.geomspace()

## Definition

`np.geomspace()` returns numbers spaced evenly on a geometric progression between two endpoints.

## Purpose

Use `np.geomspace()` when values must follow a geometric progression instead of an arithmetic or logarithmic progression.

## Real-world Use Cases

- Modeling exponential decay or growth where each step multiplies by a constant factor.
- Creating scale-invariant data for performance analysis.
- Generating geometric grids for simulations.

## Syntax

`np.geomspace(start, stop, num=50, endpoint=True, dtype=None, axis=0)`

## Parameters

| Parameter | Type | Default | Description |
| --- | --- | --- | --- |
| `start` | scalar | required | First value of the sequence. Must be non-zero and have the same sign as `stop` unless `num==1`. |
| `stop` | scalar | required | Last value of the sequence. |
| `num` | int | 50 | Number of samples. |
| `endpoint` | bool | True | If True, include `stop`. |
| `dtype` | data-type or None | None | Desired dtype for output. |
| `axis` | int | 0 | Axis in which to store the result. |

## Notes

- `start` and `stop` must have the same sign unless `num` is 1.
- The geometric sequence multiplies by a constant factor between each value.

## Common Errors

- `ValueError` when `start` and `stop` have different signs.
- `ValueError` when `start` or `stop` is zero.

In [7]:
# Generate a geometric progression from 1 to 1000 in 4 steps
geom_values = np.geomspace(1, 1000, num=4, dtype=np.float64)
print('geom_values:', geom_values)

# Create a descending geometric sequence
geom_descending = np.geomspace(1000, 1, num=4, dtype=np.float64)
print('geom_descending:', geom_descending)

geom_values: [   1.   10.  100. 1000.]
geom_descending: [1000.  100.   10.    1.]


## Edge Cases and Special Situations

This section shows how array creation functions behave with unusual data and shapes.

In [ ]:
# Empty arrays and single-element arrays
empty_zero_dim = np.array([])
single_element = np.array([42])
print('empty_zero_dim shape:', empty_zero_dim.shape)
print('single_element shape:', single_element.shape)

# Negative values and large values with np.arange and np.linspace
negative_values = np.arange(-5, 0, 1)
large_values = np.linspace(1e6, 1e7, num=5, dtype=np.float64)
print('negative_values:', negative_values)
print('large_values:', large_values)

# NaN and inf within np.full arrays
nan_array = np.full(3, np.nan, dtype=np.float64)
inf_array = np.full(3, np.inf, dtype=np.float64)
print('nan_array:', nan_array)
print('inf_array:', inf_array)

# String arrays using np.array and np.full
string_array = np.array(['apple', 'banana', 'cherry'], dtype='<U10')
string_repeat = np.full((2, 2), 'x', dtype='<U1')
print('string_array:', string_array)
print('string_repeat:', string_repeat)

# High-dimensional array creation with np.zeros and np.ones
high_dim = np.zeros((2, 2, 2, 2), dtype=np.int32)
print('high_dim shape:', high_dim.shape)

## Notes on Performance

- `np.asarray()` is often more efficient than `np.array()` for existing arrays because it avoids copies.
- `np.empty()` and `np.empty_like()` are the fastest for allocation when you plan to fill values immediately.
- `np.fromiter()` is a performant way to consume iterators without temporary Python lists.

## Best Practices

- Prefer `np.arange()` for integer ranges and `np.linspace()` for precise floating-point sequences.
- Use `np.full_like()` or `np.zeros_like()` when matching an existing array template.
- Avoid `np.empty()` outputs without initialization.

# Interview Questions

## Beginner Questions

1. What does `np.array()` do?
2. How do you create a zero-filled array?
3. What is the difference between `np.array()` and `np.asarray()`?
4. Why might `np.empty()` contain strange values?
5. How do you create an identity matrix?
6. What does `np.arange(5)` return?
7. How do you generate evenly spaced values between 0 and 1?
8. What is `np.full()` used for?
9. How does `np.zeros_like()` work?
10. When should you use `np.fromiter()`?

## Intermediate Questions

1. Explain the role of `dtype` in array creation functions.
2. How does `np.linspace()` differ from `np.arange()`?
3. What is the purpose of the `count` parameter in `np.fromiter()`?
4. When should you use `np.frombuffer()`?
5. How does `np.eye()` differ from `np.identity()`?
6. Why would you use `np.full_like()` instead of `np.full()`?
7. What happens when you call `np.array()` with nested lists of different lengths?
8. Describe the `order` parameter in `np.zeros()` and `np.ones()`.
9. How can you avoid unnecessary copies when converting array-like data?
10. When is `np.empty()` preferred over `np.zeros()`?

## Advanced Questions

1. Explain memory sharing behavior for `np.asarray()` and `np.frombuffer()`.
2. What should you watch for when using `np.logspace()` with `dtype=np.float32`?
3. How can `np.geomspace()` be used in a model hyperparameter schedule?
4. Why is `np.arange()` not always suitable for floating-point sequences?
5. Describe how `ndmin` affects the result of `np.array()`.
    
## Answers

### Beginner Answers
1. `np.array()` converts Python data into a NumPy ndarray.
2. Use `np.zeros(shape)` to create a zero-filled array.
3. `np.asarray()` avoids copies when the input is already an ndarray, while `np.array()` creates a new array by default.
4. `np.empty()` allocates memory without initialization, so existing memory contents appear as random values.
5. Use `np.eye(n)` or `np.identity(n)` for an identity matrix.
6. `np.arange(5)` returns `[0, 1, 2, 3, 4]`.
7. `np.linspace(0, 1, num)` returns a fixed number of samples with a guaranteed endpoint.
8. `np.full(shape, fill_value)` fills an array with a constant value.
9. `np.zeros_like()` creates zeros with the same shape and dtype as another array.
10. Use `np.fromiter()` when you want to convert an iterator into an ndarray efficiently.

### Intermediate Answers
1. `dtype` controls the element type and memory layout, affecting performance and precision.
2. `np.linspace()` generates a fixed number of samples across an interval, while `np.arange()` generates values at fixed steps.
3. `count` determines how many items to read from the iterable; use it to reserve array size.
4. `np.frombuffer()` interprets raw binary memory as an ndarray without copying.
5. `np.eye()` can create rectangular matrices and offset diagonals, while `np.identity()` creates a square main-diagonal matrix.
6. `np.full_like()` uses the shape and dtype of an existing array, avoiding manual shape repetition.
7. NumPy creates an object array or raises a ValueError depending on the dtype and level of nesting.
8. `order` controls whether the output is row-major or column-major in memory.
9. Use `np.asarray()` or pass `copy=False` to `np.array()` for existing ndarrays.
10. Use `np.empty()` when you will overwrite every element, because it avoids the initialization cost of zeros.

### Advanced Answers
1. `np.asarray()` may return a view of the original array, while `np.frombuffer()` shares raw buffer memory and can create a read-only view for immutable buffers.
2. Floating-point precision can cause the generated values to be slightly off; use `np.float64` or `np.linspace()` for more predictable spacing.
3. `np.geomspace()` can schedule hyperparameters such as learning rates that decay geometrically between two endpoints.
4. Floating-point step values may accumulate rounding errors in `np.arange()`, leading to unexpected endpoints.
5. `ndmin` pads the array with additional dimensions of size 1 on the left.

# Practice Problems

## Easy Problems

1. Create an array of zeros with shape `(3, 2)`.
2. Convert the list `[5, 10, 15]` into a NumPy array of type `np.float32`.
3. Create a 5-element array with values from 0 to 4 using `np.arange()`.
4. Build an identity matrix of size 4 using `np.eye()`.
5. Create an array of ones with the same shape as `np.array([[1, 2], [3, 4]])`.

## Medium Problems

1. Create a 1-D array with 20 values evenly spaced between `-1` and `1` using `np.linspace()`.
2. Use `np.fromiter()` to convert the generator `(i * 2 for i in range(10))` into an integer array.
3. Create a 3x5 array filled with the constant value `42` using `np.full()`.
4. Create a rectangular matrix with ones on the diagonal above the main diagonal using `np.eye()`.
5. Generate a geometric progression from `1e-3` to `1e3` with 7 values using `np.geomspace()`.

## Hard Problems

1. Use `np.frombuffer()` to interpret a `bytearray` containing `b'01000200'` as two `np.uint16` values.
2. Create a 3-D array of shape `(2, 2, 2)` filled with ones and then create an empty array with the same shape using `np.empty_like()`.
3. Generate 50 logarithmically spaced values between `10^2` and `10^5` using `np.logspace()` and compute their base-10 logarithm to verify the spacing.
4. Create an array of shape `(1, 5)` from a list using `np.array()` and `ndmin=2`, then confirm the resulting shape.
5. Explain the difference in memory behavior between `np.array(existing_array, copy=False)` and `np.asarray(existing_array)`.

# Summary

## Key Points

- Use `np.array()` to build a new ndarray from Python sequences.
- Use `np.asarray()` to convert input to ndarray while avoiding copies when possible.
- Use `np.fromiter()` for iterables and generators.
- Use `np.frombuffer()` to interpret raw binary buffers without copying.
- Use factory functions such as `np.zeros()`, `np.ones()`, `np.full()`, `np.eye()`, and `np.identity()` for initialization.
- Use `np.arange()` for integer ranges and `np.linspace()` or `np.logspace()` for precise sample counts.
- `np.geomspace()` is ideal for geometric progressions.

## Cheat Sheet

- `np.array(object)` — new array from array-like data.
- `np.asarray(a)` — convert to ndarray while reusing existing memory if possible.
- `np.fromiter(iterable, dtype, count)` — build from iterable.
- `np.frombuffer(buffer, dtype)` — interpret raw bytes.
- `np.zeros(shape)` — filled with 0.
- `np.ones(shape)` — filled with 1.
- `np.full(shape, fill_value)` — filled with constant.
- `np.eye(N)` / `np.identity(n)` — identity matrix.
- `np.arange()` — step-based range.
- `np.linspace()` — fixed count, endpoint optional.
- `np.logspace()` — log-scale spacing.
- `np.geomspace()` — geometric spacing.

## Memory Tricks

- Prefer `np.asarray()` for conversion when input may already be ndarray.
- Use `np.empty()` only when you will overwrite values before reading.
- Use `dtype` carefully to balance precision and memory usage.

## Best Practices

- Always choose the array creation function that most closely matches your intent.
- Favor `np.linspace()` over `np.arange()` for floating-point sequences with a fixed number of samples.
- Match shapes with `*_like()` variants to avoid dimension mismatch errors.

## Common Mistakes

- Assuming `np.empty()` initializes values to zero.
- Using `np.arange()` for non-integer steps without considering floating-point rounding.
- Forgetting that `np.asarray()` may share memory with its input.

## Interview Tips

- Explain the difference between copy and view behavior in array creation.
- Mention performance tradeoffs between `np.array()` and `np.asarray()`.
- Demonstrate understanding of how `np.linspace()`, `np.logspace()`, and `np.geomspace()` differ.
- Show awareness of dtype selection and memory layout when initializing large arrays.